### ISSUE TITLE
Recommend setting `terrain = DISABLED` in `surveyor.toml` for servers

### ISSUE THREAD

**Issue by sleepingdragoninn** [SettingDust/SurveyorAtlases#1]
Hi hello! Cool addon - I think you're the first non-nepotism surveyor consumer! Feel free to hit up our issues for any API improvements you could use.

You're totally correctly using the dynamic init for the surveyor structure and landmark systems

![image](https://github.com/user-attachments/assets/a8e11d42-0a0b-4d9e-b2ac-504936d4f25f)

despite this, on dedicated servers, surveyor will still turn on the terrain system by default just in case clients using different map mods want terrain sync.

Because map atlases is a mixed side map mod, you can add a recommendation in the description for dedicated server users to set `terrain = DISABLED` to save performance and save size.

That's all! Thanks ^^

**Comment by SettingDust** [comment]
https://github.com/SettingDust/SurveyorAtlases/commit/b9414afccca9633834abba0178212b797e8f4f69
